import React, { useState, useEffect, ChangeEvent } from 'react';
import { motion } from 'framer-motion';
import { 
  FileText,
  Hash,
  Image as ImageIcon,
  Calendar,
  BarChart2,
  ChevronRight,
  Sparkles,
  Send,
  Clock,
  MessageSquare,
  Award,
  TrendingUp,
  Mic2,
  Shield
} from 'lucide-react';
import { useThemeStyles } from '@/lib/theme-utils';
import ProductLayout from '@/components/Layout/ProductLayout';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

type VisualSuggestion = {
  type: string;
  description: string;
};

type OptimalTime = {
  day: string;
  time: string;
  engagement: string;
};

const LinkedInContentPage = () => {
  const themeStyles = useThemeStyles();
  const [mounted, setMounted] = useState(false);
  const [activeTab, setActiveTab] = useState('composer');
  const [characterCount, setCharacterCount] = useState(0);
  const [readabilityScore, setReadabilityScore] = useState(0);
  const [postContent, setPostContent] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return null;
  }

  const handleGenerate = () => {
    setIsGenerating(true);
    // Simulate API call
    setTimeout(() => {
      setIsGenerating(false);
      setPostContent("Here's a sample post generated by our AI. This post is designed to engage your audience and drive meaningful interactions. Customize it further to match your personal style!");
      setCharacterCount(180);
      setReadabilityScore(85);
    }, 1500);
  };

  // Home-page style hero and features
  const features = [
    {
      icon: <Sparkles className="w-8 h-8 text-blue-600" />,
      title: "AI-Powered Writing",
      description: "Generate engaging LinkedIn posts in seconds with advanced AI."
    },
    {
      icon: <Hash className="w-8 h-8 text-purple-600" />,
      title: "Trending Hashtags",
      description: "Get hashtag suggestions to maximize your post reach."
    },
    {
      icon: <ImageIcon className="w-8 h-8 text-green-600" />,
      title: "Image Suggestions",
      description: "Enhance your posts with relevant image recommendations."
    },
    {
      icon: <BarChart2 className="w-8 h-8 text-yellow-600" />,
      title: "Performance Insights",
      description: "Track engagement and optimize your content strategy."
    }
  ];


  const trendingHashtags: string[] = [
    "#CareerGrowth",
    "#AIInnovation",
    "#TechJobs",
    "#DigitalTransformation",
    "#ProfessionalDevelopment"
  ];
  
  const visualSuggestions: VisualSuggestion[] = [
    {
      type: "Infographic",
      description: "Data visualization of industry trends"
    },
    {
      type: "Office Photo",
      description: "Workspace setup with laptop and notebook"
    },
    {
      type: "Quote Graphic",
      description: "Inspirational quote with minimalist design"
    }
  ];
  
  const optimalTimes: OptimalTime[] = [
    {
      day: "Tuesday",
      time: "10:30 AM",
      engagement: "High"
    },
    {
      day: "Wednesday",
      time: "8:15 AM",
      engagement: "Peak"
    },
    {
      day: "Friday",
      time: "12:00 PM",
      engagement: "Medium"
    }
  ];

  const handleContentChange = (e: ChangeEvent<HTMLTextAreaElement>): void => {
    const content = e.target.value;
    setPostContent(content);
    setCharacterCount(content.length);
    // Simple readability calculation (for demo purposes)
    setReadabilityScore(Math.min(100, Math.floor(content.length / 5)));
  };

  return (
    <ProductLayout 
      title="LinkedIn Post Builder"
      description="Create engaging, professional LinkedIn posts that stand out and drive engagement"
    >
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-blue-50 to-purple-50 py-20 text-center relative overflow-hidden">
        <div className="max-w-3xl mx-auto px-4">
          <motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="text-4xl md:text-5xl font-extrabold mb-6 text-blue-900">
            LinkedIn Post Builder
          </motion.h1>
          <motion.p initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="text-xl md:text-2xl text-blue-700 mb-8">
            Craft compelling, engaging LinkedIn posts in seconds. Leverage AI to boost your professional presence.
          </motion.p>
          <Button size="lg" className="bg-blue-700 text-white hover:bg-blue-800 font-medium">
            Start Creating
          </Button>
        </div>
        {/* Decorative shapes */}
        <div className="absolute -top-16 -right-16 w-48 h-48 rounded-full bg-blue-200/30"></div>
        <div className="absolute -bottom-16 -left-16 w-72 h-72 rounded-full bg-purple-200/20"></div>
      </section>

      {/* Features Section */}
      <section className="max-w-5xl mx-auto py-16 px-4 grid grid-cols-1 md:grid-cols-2 gap-8">
        {features.map((feature, idx) => (
          <div key={idx} className="bg-white rounded-2xl shadow-lg p-8 flex flex-col items-center text-center">
            <div className="mb-4">{feature.icon}</div>
            <h3 className="text-xl font-bold mb-2 text-blue-900">{feature.title}</h3>
            <p className="text-blue-700">{feature.description}</p>
          </div>
        ))}
      </section>

      {/* Main Product Content */}
      <div className={`min-h-screen ${themeStyles.bgGradient} text-${themeStyles.textPrimary} transition-colors duration-300`}>
        {/* Hero Section */}
        <section className="relative py-20 overflow-hidden">
          {/* Animated Background */}
          <div className="absolute inset-0 overflow-hidden">
            <motion.div 
              className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-96 h-96 border-2 border-cyan-500/10 rounded-full"
              animate={{ rotate: 360 }}
              transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
            />
            <motion.div 
              className="absolute top-20 right-32 w-48 h-48 border border-purple-500/20 rounded-full"
              animate={{
                rotate: -360,
                x: [0, 30, 0, -30, 0],
                y: [0, -15, 0, 15, 0],
              }}
              transition={{
                rotate: { duration: 25, repeat: Infinity, ease: "linear" },
                x: { duration: 12, repeat: Infinity, ease: "easeInOut" },
                y: { duration: 8, repeat: Infinity, ease: "easeInOut" },
              }}
            />
          </div>
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
            <div className="text-center mb-12">
              <h1 className={`text-4xl font-bold mb-4 ${themeStyles.textPrimary}`}>LinkedIn Content Generator</h1>
              <p className={`text-xl ${themeStyles.textSecondary} max-w-3xl mx-auto`}>Create engaging LinkedIn posts with AI assistance.</p>
              <span className="text-sm font-medium text-white/90">LinkedIn Content Generator</span>
            </div>
            <motion.h1
              className="text-4xl lg:text-6xl font-bold leading-tight text-white mb-6"
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
            >
              <span className="block">Craft </span>
              <span className="bg-gradient-to-r from-cyan-400 via-purple-400 to-pink-400 bg-clip-text text-transparent">Engaging Content</span>
              <span className="block">That Gets Noticed</span>
            </motion.h1>
            <motion.p
              className="text-xl text-white/80 max-w-2xl mx-auto mb-8"
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
            >
              AI-powered tools to elevate your personal brand and maximize engagement
            </motion.p>
          </div>
        </section>
              </div>
        {/* Content Generator Section */}
        {/* ...rest of the product UI... */}
    </ProductLayout>
  );
};

export default LinkedInContentPage;
//                             <div className={`px-3 py-1 rounded-full text-xs font-medium ${
//                               time.engagement === 'Peak' ? 'bg-indigo-500/20 text-indigo-400' : 
//                               time.engagement === 'High' ? 'bg-green-500/20 text-green-400' : 'bg-yellow-500/20 text-yellow-400'
//                             }`}>
//                               {time.engagement}
//                             </div>
//                           </div>
//                         </motion.div>
//                       ))}
//                     </div>
//                   </div>
                  
//                   <div className="grid md:grid-cols-2 gap-6">
//                     <div className="bg-gradient-to-r from-indigo-500/10 to-blue-500/10 p-6 rounded-lg border border-indigo-500/20">
//                       <h4 className="text-lg font-bold text-white mb-3">Engagement Forecast</h4>
//                       <div className="h-32 bg-white/5 rounded flex items-center justify-center mb-3">
//                         <BarChart2 className="w-12 h-12 text-indigo-400/50" />
//                       </div>
//                       <p className="text-white/80">Based on similar posts in your network, this content is predicted to receive 25-40% more engagement than your average post.</p>
//                     </div>
                    
//                     <div className="bg-white/5 rounded-lg border border-white/10 p-6">
//                       <h4 className="text-lg font-bold text-white mb-3">Schedule Your Post</h4>
//                       <div className="mb-4">
//                         <label className="block text-sm text-white/70 mb-1">Select Date & Time</label>
//                         <input 
//                           type="datetime-local" 
//                           className="w-full bg-white/5 border border-white/10 rounded-lg px-4 py-2 text-white focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-transparent" 
//                         />
//                       </div>
//                       <button className="w-full bg-gradient-to-r from-indigo-500 to-blue-600 text-white py-2 rounded-lg hover:shadow-lg hover:shadow-indigo-500/25 transition-all">
//                         Schedule Post
//                       </button>
//                     </div>
//                   </div>
//                 </motion.div>
//               )}
//             </div>
            
//             {/* Footer CTA */}
//             <div className="bg-gradient-to-r from-slate-800/50 to-slate-900/50 p-6 border-t border-white/10">
//               <div className="flex flex-col md:flex-row items-center justify-between gap-4">
//                 <div className="text-white/80">
//                   Ready to publish your LinkedIn content?
//                 </div>
//                 <div className="flex gap-3">
//                   <button className="bg-white/10 backdrop-blur-sm text-white px-6 py-3 rounded-lg border border-white/20 hover:bg-white/20 transition-all">
//                     Save Draft
//                   </button>
//                   <button className="bg-gradient-to-r from-cyan-500 to-purple-600 text-white px-6 py-3 rounded-lg hover:shadow-lg hover:shadow-purple-500/25 transition-all flex items-center gap-2">
//                     <Send className="w-5 h-5" />
//                     Publish Now
//                   </button>
//                 </div>
//               </div>
//             </div>
//           </div>
//         </div>
//       </section>

//       {/* Success Metrics Section */}
//       <section className="relative py-20">
//         <div className="absolute inset-0 bg-gradient-to-b from-slate-900/80 via-slate-900/50 to-slate-900/80" />
//         <div className="relative z-10 max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
//           <motion.div 
//             className="text-center mb-16"
//             initial={{ opacity: 0, y: 30 }}
//             whileInView={{ opacity: 1, y: 0 }}
//             viewport={{ once: true }}
//           >
//             <h2 className="text-3xl lg:text-4xl font-bold text-white mb-6">
//               <span className="bg-gradient-to-r from-cyan-400 to-purple-400 bg-clip-text text-transparent">
//                 AI-Generated Content
//               </span>{" "}
//               Performs Better
//             </h2>
//             <p className="text-xl text-white/80 max-w-3xl mx-auto">
//               Our users see measurable improvements in their LinkedIn engagement
//             </p>
//           </motion.div>

//           <div className="grid md:grid-cols-3 gap-8">
//             <motion.div
//               className="bg-white/5 backdrop-blur-sm rounded-2xl p-8 border border-white/10 text-center"
//               initial={{ opacity: 0, y: 50 }}
//               whileInView={{ opacity: 1, y: 0 }}
//               viewport={{ once: true }}
//               transition={{ duration: 0.6 }}
//             >
//               <div className="text-5xl font-bold bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent mb-4">
//                 2.4x
//               </div>
//               <h3 className="text-xl font-bold text-white mb-2">More Profile Views</h3>
//               <p className="text-white/70">Users who post weekly</p>
//             </motion.div>
            
//             <motion.div
//               className="bg-white/5 backdrop-blur-sm rounded-2xl p-8 border border-white/10 text-center"
//               initial={{ opacity: 0, y: 50 }}
//               whileInView={{ opacity: 1, y: 0 }}
//               viewport={{ once: true }}
//               transition={{ duration: 0.6, delay: 0.2 }}
//             >
//               <div className="text-5xl font-bold bg-gradient-to-r from-purple-400 to-pink-500 bg-clip-text text-transparent mb-4">
//                 68%
//               </div>
//               <h3 className="text-xl font-bold text-white mb-2">Higher Engagement</h3>
//               <p className="text-white/70">On AI-optimized posts</p>
//             </motion.div>
            
//             <motion.div
//               className="bg-white/5 backdrop-blur-sm rounded-2xl p-8 border border-white/10 text-center"
//               initial={{ opacity: 0, y: 50 }}
//               whileInView={{ opacity: 1, y: 0 }}
//               viewport={{ once: true }}
//               transition={{ duration: 0.6, delay: 0.4 }}
//             >
//               <div className="text-5xl font-bold bg-gradient-to-r from-green-400 to-teal-500 bg-clip-text text-transparent mb-4">
//                 5.7x
//               </div>
//               <h3 className="text-xl font-bold text-white mb-2">More Connection Requests</h3>
//               <p className="text-white/70">For active content creators</p>
//             </motion.div>
//           </div>
//         </div>
//       </section>
    
//   );
// };

// export default LinkedInContentPage;